version: 2
jobs:
  build:
    working_directory: /home/linux-dev-workstation
    docker:
      - image: c2v4/vagrant-virtualbox
        user: root

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install plugin
          command: |
            vagrant plugin install vagrant-disksize
      - run:
          name: Create an image
          command: |
            sh build.sh ${VAGRANT_CLOUD_TOKEN} ${CIRCLE_BUILD_NUM}
